name: Release Dispatcher
on:
  release:
    types:
      - created

jobs:
  dispatch:
    name: Dispatch
    env:
      PACKAGES_TO_UPGRADE: ${{ needs.run_publish.outputs.packages }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['moddio/gs']
    timeout-minutes: 5
    steps:
      - name: Determine release version
        id: version
        run: echo ::set-output name=VERSION::${{ github.event.release.tag_name }}
      - name: Set release type
        id: set_event_type
        run: |
          if [[ "${{ steps.version.outputs.VERSION }}" == *"-staging" ]]; then
            echo "Updating event type to moddio2_staging_post_release"
            event_type="moddio2_staging_post_release"
          else
            echo "Updating event type to moddio2_post_release"
            event_type="moddio2_post_release"
          fi
          echo "::set-output name=EVENT_TYPE::$event_type"
      - name: Dispatch to moddio/gs
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.MODDIO2_DISPATCH_TOKEN }}" \
            --request POST \
            --data '{"event_type": "moddio2_post_release", "client_payload": { "version": "${{ steps.version.outputs.VERSION }}" }}' https://api.github.com/repos/moddio/gs/dispatches
      - name: Dispatch to moddio/be
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.MODDIO2_DISPATCH_TOKEN }}" \
            --request POST \
            --data '{"event_type": "${{ steps.set_event_type.outputs.EVENT_TYPE }}", "client_payload": { "version": "${{ steps.version.outputs.VERSION }}" }}' https://api.github.com/repos/moddio/be/dispatches
